### ISSUE TITLE
fix login/logout/register in navigation

### ISSUE THREAD

**Issue by wykhuh** [LearnToCodeLA/marsrocks#42]
Currently we are always showing the login, register, and logout links. We want to show/hide those links depending on if the user is logged in.

For visitors, show login and register links.
For logged in users, show logout and username.

**Comment by wykhuh** [comment]
For visitors, show login and register links.
For logged in users, show logout and username.

**Comment by benmont99** [comment]
need to edit project/templates/layout  file
will need to use {%   %}  to embed the if else, etc.
see jinja templates docs
